# Copyright (c) 2025 Nordic Semiconductor
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause

manifest:
  self:
    import: submanifests

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect

  projects:
    - name: nrf
      remote: ncs
      repo-path: sdk-nrf
      revision: v3.3.0-preview2
      import:
        name-allowlist:
          - cjson
          - cmsis_6
          - cmock
          - hal_nordic
          - mbedtls
          - mcuboot
          - memfault-firmware-sdk
          - nrfxlib
          - oberon-psa-crypto
          - segger
          - trusted-firmware-m
          - zcbor
          - zephyr
          #- openthread
          #- azure-sdk-for-c
          #- matter
